// Tool 3
import {z} from "zod";
import Groq from 'groq-sdk';

const groq = new Groq({ apiKey: process.env.GROQ_API_KEY })

export const runComplianceAuditTool = {
    name: 'run_compliance_audit',
    description: 'Systematically reviews the isolated interview text to determine if the recruiter strictly adhered to mandatory compliance guidelines.',
    schema: {
        interviewTranscript: z.string().describe("The cleaned and isolated interview transcript text generated by the isolation tool.")
    },
    handler: async ({interviewTranscript}) => {
        if (!interviewTranscript) {
            console.error("Interview transcript unavailable");
            return {
                isError: true,
                content: [{type: 'text', text: `Interview transcript unavailable`}]
            };
        }

        try {
            const response = await groq.chat.completions.create({
                model: "llama-3.3-70b-versatile",
                temperature: 0.1, // low temp for analytical evaluation
                messages: [
                    {
                        role: "system",
                        // TODO: Update the QA Agency Checklist
                        content: `You are an automated Quality Assurance (QA) Officer auditing a recruiter's interview transcript. 
Your task is to systematically evaluate if the recruiter adhered to mandatory compliance guidelines.

CRITICAL CONSTRAINT - ONE-SIDED TRANSCRIPT: 
The transcript may only contain the recruiter's voice. You must infer the candidate's answers based on the recruiter's context, acknowledgments, or conversational flow. For example, if the recruiter asks about work authorization and then responds with "Great, that works perfectly," you must deduce that the candidate provided a satisfactory answer, and grade the checkpoint as a "PASS".

Standard Agency QA Checklist:   
1. Legal Work Authorization: Did the recruiter verify if the candidate is legally authorized to work?
2. Salary Range: Did the recruiter explicitly state the salary range for the role?
3. Notice Period: Did the recruiter confirm the candidate's notice period or availability to start?

OUTPUT INSTRUCTIONS:
You must output strictly in JSON format. The JSON object must contain a single key "audit_report" which is an array of objects. 
Each object must have exactly the following keys:
- "checkpoint": The name of the checkpoint (e.g., "Work Authorization", "Salary Range", "Notice Period").
- "status": Strictly use "PASS", "FAIL", or "NOT_APPLICABLE".
- "reasoning": A brief explanation justifying the status based on evidence (or inferred evidence) from the transcript.`
                    },
                    {
                        role: "user",
                        content: interviewTranscript
                    }
                ],
                // Force structured JSON output with `type: json_object` because json_schema isn't strictly necessary as we outline in prompt, but we can also use json_schema for absolute rigid structure like earlier! Let's use json_object as requested.
                response_format: {type: "json_object"}
            });

            const parsedResponse = JSON.parse(response.choices[0].message.content);

            return {
                isError: false,
                content: [{type: "text", text: JSON.stringify(parsedResponse, null, 2)}]
            };

        } catch (err) {
            console.error(`Compliance Audit Error: ${err}`);
            return {
                isError: true,
                content: [{type: "text", text: `Compliance audit failed: ${err.message}`}]
            };
        }
    }
}